export const characterNames = [
  "3-D Man",
  "A-Bomb (HAS)",
  "A.I.M.",
  "Aaron Stack",
  "Abomination (Emil Blonsky)",
  "Abomination (Ultimate)",
  "Absorbing Man",
  "Abyss",
  "Abyss (Age of Apocalypse)",
  "Adam Destine",
  "Adam Warlock",
  "Aegis (Trey Rollins)",
  "Aero (Aero)",
  "Agatha Harkness",
  "Agent Brand",
  "Agent X (Nijo)",
  "Agent Zero",
  "Agents of Atlas",
  "Aginar",
  "Air-Walker (Gabriel Lan)",
  "Ajak",
  "Ajaxis",
  "Akemi",
  "Alain",
  "Albert Cleary",
  "Albion",
  "Alex Power",
  "Alex Wilder",
  "Alexa Mendez",
  "Alexander Pierce",
  "Alice",
  "Alicia Masters",
  "Alpha Flight",
  "Alpha Flight (Ultimate)",
  "Alvin Maker",
  "Amadeus Cho",
  "Amanda Sefton",
  "Amazoness",
  "American Eagle (Jason Strongbow)",
  "Amiko",
  "Amora",
  "Amphibian (Earth-712)",
  "Amun",
  "Ancient One",
  "Ancient One (Ultimate)",
  "Angel (Angel Salvadore)",
  "Angel (Thomas Halloway)",
  "Angel (Ultimate)",
  "Angel (Warren Worthington III)",
  "Angela (Aldrif Odinsdottir)",
  "Anita Blake",
  "Anne Marie Hoag",
  "Annihilus",
  "Anole",
  "Ant-Man (Eric O'Grady)",
  "Ant-Man (Hank Pym)",
  "Ant-Man (Scott Lang)",
  "Anthem",
  "Apocalypse",
  "Apocalypse (Ultimate)",
  "Aqueduct",
  "Arachne",
  "Araña",
  "Arcade",
  "Arcana",
  "Archangel",
  "Arclight",
  "Ares",
  "Argent",
  "Armadillo",
  "Armor (Hisako Ichiki)",
  "Armory",
  "Arnim Zola",
  "Arsenic",
  "Artiee",
  "Asgardian",
  "Askew-Tronics",
  "Asylum",
  "Atlas (Team)",
  "Attuma",
  "Aurora",
  "Avalanche",
  "Avengers",
  "Avengers (Ultimate)",
  "Azazel (Mutant)",
  "Balder",
  "Banshee",
  "Banshee (Theresa Rourke)",
  "Baron Mordo (Karl Mordo)",
  "Baron Strucker",
  "Baron Zemo (Heinrich Zemo)",
  "Baron Zemo (Helmut Zemo)",
  "Baroness S'Bak",
  "Barracuda",
  "Bart Rozum",
  "Bastion",
  "Batroc the Leaper",
  "Battering Ram",
  "Battlestar",
  "Beak",
  "Daredevil (LEGO Marvel Super Heroes)",
  "Daredevil (Marvel Heroes)",
  "Daredevil (Ultimate)",
  "Dargo Ktor",
  "Dark Avengers",
  "Dark Beast",
  "Dark Phoenix",
  "Dark X-Men",
  "Darkhawk",
  "Darkstar",
  "Darwin",
  "Dazzler",
  "Dazzler (Ultimate)",
  "Deacon Frost",
  "Dead Girl",
  "Deadpool",
  "Deadpool (Deadpool)",
  "Deadpool (LEGO Marvel Super Heroes)",
  "Deadpool (X-Men: Battle of the Atom)",
  "Death",
  "Deathbird",
  "Deathcry",
  "Deathlok",
  "Deathstrike (Ultimate)",
  "Debra Whitman",
  "Debrii",
  "Deena Pilgrim",
  "Defenders",
  "Demogoblin",
  "Destiny",
  "Detective Soap",
  "Deviants",
  "Devil Dinosaur (Devil Dinosaur)",
  "Devil Dinosaur (HAS)",
  "Devos",
  "Dexter Bennett",
  "Diablo",
  "Diamondback (Rachel Leighton)",
  "Dinah Soar",
  "Dirk Anger",
  "Doc Samson",
  "Doctor Doom",
  "Doctor Doom (Ultimate)",
  "Doctor Faustus",
  "Doctor Octopus",
  "Doctor Octopus (Ultimate)",
  "Doctor Spectrum",
  "Doctor Strange",
  "Doctor Strange (Ultimate)",
  "Doctor Voodoo",
  "Dog Brother #1",
  "Domino",
  "Donald Blake",
  "Doomsday Man",
  "Doop",
  "Doorman",
  "Dora Milaje",
  "Dorian Gray",
  "Dormammu",
  "Dormammu (Ultimate)",
  "Dr. Strange (Marvel: Avengers Alliance)",
  "Dracula",
  "Dragon Lord",
  "Dragon Man",
  "Drax",
  "Dreadnoughts",
  "Dreaming Celestial",
  "Druig",
  "Dum Dum Dugan",
  "Dust",
  "Earthquake",
  "Echo",
  "Eddie Brock",
  "Eddie Lau",
  "Edward 'Ted' Forrester",
  "Edwin Jarvis",
  "Ego",
  "Electro",
  "Electro (Ultimate)",
  "Elektra",
  "Elektra (Ultimate)",
  "Elements of Doom",
  "Elite",
  "Elixir",
  "Elloe Kaifi",
  "Elsa Bloodstone",
  "Emma Frost",
  "Empath",
  "Emplate",
  "Enchantress (Amora)",
  "Enchantress (Sylvie Lushton)",
  "Ender Wiggin",
  "Energizer",
  "Epoch",
  "Erik the Red",
  "Eternals",
  "Eternity",
  "Excalibur",
  "Executioner (Skurge)",
  "Exiles",
  "Gunslinger",
  "GW Bridge",
  "Gwen Stacy",
  "Gwen Stacy (Ultimate)",
  "H.A.M.M.E.R.",
  "H.E.R.B.I.E.",
  "Hairball",
  "Half-Life (Tony Masterson)",
  "Hammerhead",
  "Hammerhead (Ultimate)",
  "Hank Pym",
  "Hannibal King",
  "Happy Hogan",
  "Hardball",
  "Harley Davidson Cooper",
  "Harpoon",
  "Harrier",
  "Harry Heck",
  "Harry Osborn",
  "Harry Osborn (Ultimate)",
  "Hate-Monger (Adolf Hitler)",
  "Havok",
  "Hawkeye",
  "Hawkeye (Kate Bishop)",
  "Hawkeye (Marvel Heroes)",
  "Hawkeye (Ultimate)",
  "Hawkeye/Clint Barton (MAA)",
  "Hecate (Ravonna Renslayer)",
  "Hedge Knight",
  "Hela",
  "Hellcat (Patsy Walker)",
  "Hellfire Club",
  "Hellfire Club (Ultimate)",
  "Hellion",
  "Hellions (Squad)",
  "Hemingway",
  "Henry Peter Gyrich",
  "Hepzibah",
  "Hercules",
  "Heroes For Hire",
  "Hex",
  "High Evolutionary",
  "Hindsight Lad",
  "Hiroim",
  "Hit-Monkey",
  "Hitman",
  "Hitomi Sakuma",
  "Hobgoblin (Jason Macendale)",
  "Hobgoblin (Robin Borne)",
  "Hobgoblin (Roderick Kingsley)",
  "Holocaust (Age of Apocalypse)",
  "Holy",
  "Honey Badger (Gabrielle Kinney)",
  "Hope Summers",
  "Howard Saint",
  "Howard The Duck",
  "Hulk",
  "Hulk (HAS)",
  "Hulk (LEGO Marvel Super Heroes)",
  "Hulk (Marvel Zombies)",
  "Hulk (Marvel: Avengers Alliance)",
  "Hulk (Ultimate)",
  "Hulk-dok",
  "Hulk/Bruce Banner (MAA)",
  "Hulkling",
  "Human Cannonball",
  "Human Fly (Richard Deacon)",
  "Human Robot",
  "Human Torch",
  "Human Torch (Jim Hammond)",
  "Human Torch (Ultimate)",
  "Humbug",
  "Husk",
  "Hussar",
  "Hydra",
  "Hydro-Man",
  "Hyperion (Earth-712)",
  "Hypno-Hustler",
  "Iceman",
  "Iceman (Ultimate)",
  "Iceman (X-Men: Battle of the Atom)",
  "Ikaris",
  "Illuminati",
  "Ilyana Rasputin",
  "Immortus",
  "Imp",
  "Imperfects",
  "Imperial Guard",
  "Impossible Man",
  "In-Betweener",
  "Inertia",
  "Infant Terrible",
  "Inhumans",
  "Ink",
  "Invaders",
  "Invisible Woman",
  "Invisible Woman (Marvel: Avengers Alliance)",
  "Invisible Woman (Ultimate)",
  "Iron Cross Army",
  "Iron Fist (Bei Bang-Wen)",
  "Exodus",
  "Expediter",
  "Ezekiel",
  "Ezekiel Stane",
  "Fabian Cortez",
  "Falcon",
  "Falcon/Sam Wilson (MAA)",
  "Fallen One",
  "Famine",
  "Fantastic Four",
  "Fantastic Four (Ultimate)",
  "Fantastick Four",
  "Fantomex",
  "Fat Cobra",
  "Felicia Hardy",
  "Fenris",
  "Feral",
  "Fin Fang Foom",
  "Firebird",
  "Firebrand",
  "Firedrake",
  "Firelord",
  "Firestar",
  "Firestar (Ultimate)",
  "Fixer (Paul Norbert Ebersol)",
  "Flatman",
  "Flying Dutchman",
  "Foggy Nelson",
  "Force Works",
  "Forearm",
  "Forge",
  "Forge (Ultimate)",
  "Forgotten One",
  "Frank Castle",
  "Frankenstein's Monster",
  "Franklin Richards",
  "Franklin Storm",
  "Freak",
  "Frenzy",
  "Frightful Four",
  "Frog Thor",
  "Frog-Man",
  "Gabe Jones",
  "Galactus",
  "Galia",
  "Gambit",
  "Gamma Corps",
  "Gamora",
  "Gamora (Marvel War of Heroes)",
  "Gargoyle",
  "Gargoyle (Isaac Christians)",
  "Gargoyle (Yuri Topolov)",
  "Garia",
  "Garrison Kane",
  "Gateway",
  "Gauntlet (Joseph Green)",
  "Geiger",
  "Gene Sailors",
  "Generation X",
  "Genesis",
  "Genis-Vell",
  "George Stacy (Ultimate)",
  "Gertrude Yorkes",
  "Ghost Rider (Daniel Ketch)",
  "Ghost Rider (Johnny Blaze)",
  "Ghost Rider (Marvel War of Heroes)",
  "Ghost Rider (Robbie Reyes)",
  "Giant Girl",
  "Giant Man",
  "Giant-dok",
  "Giant-Man (Ultimate)",
  "Gideon",
  "Gilgamesh",
  "Git Hoskins",
  "Gladiator (Kallark)",
  "Gladiator (Melvin Potter)",
  "Glenn Talbot",
  "Glorian",
  "Goblin Queen",
  "Golden Guardian",
  "Goliath (Bill Foster)",
  "Gorgon",
  "Gorgon (Inhumans)",
  "Gorilla Man",
  "Grandmaster",
  "Graviton",
  "Gravity",
  "Great Lakes Avengers",
  "Green Goblin (Barry Norman Osborn)",
  "Green Goblin (Harry Osborn)",
  "Green Goblin (Norman Osborn)",
  "Green Goblin (Ultimate)",
  "Gressill",
  "Grey Gargoyle",
  "Greymalkin",
  "Grim Reaper",
  "Groot",
  "Guardian",
  "Guardians of the Galaxy",
  "Guardsmen",
  "Captain America (House of M)",
  "Captain America (LEGO Marvel Super Heroes)",
  "Captain America (Marvel War of Heroes)",
  "Captain America (Sam Wilson)",
  "Captain America (Ultimate)",
  "Captain America/Steve Rogers (MAA)",
  "Captain Britain",
  "Captain Britain (Betsy Braddock)",
  "Captain Britain (Ultimate)",
  "Captain Cross",
  "Captain Flint",
  "Captain Marvel (Carol Danvers)",
  "Captain Marvel (Genis-Vell)",
  "Captain Marvel (Mar-Vell)",
  "Captain Marvel (Monica Rambeau)",
  "Captain Marvel (Phyla-Vell)",
  "Captain Midlands",
  "Captain Stacy",
  "Captain Universe",
  "Cardiac",
  "Caretaker",
  "Cargill",
  "Carlie Cooper",
  "Carmella Unuscione",
  "Carnage",
  "Carnage (Ultimate)",
  "Carol Danvers",
  "Carol Hines",
  "Carrion (Malcolm McBride)",
  "Cassandra Nova",
  "Catseye",
  "Cecilia Reyes",
  "Celestials",
  "Centennial",
  "Centurions",
  "Cerebro",
  "Cerise",
  "Ch'od",
  "Chamber",
  "Chameleon",
  "Champions",
  "Changeling",
  "Charles Xavier",
  "Charlie Campion",
  "Charlie-27",
  "Chase Stein",
  "Chat",
  "Chimera",
  "Chores MacGillicudy",
  "Christian Walker",
  "Chronomancer",
  "Chthon",
  "ClanDestine",
  "Clea",
  "Clea (Ultimate)",
  "Clint Barton",
  "Cloak",
  "Cloud 9",
  "Cobalt Man",
  "Colleen Wing",
  "Colonel America",
  "Colossus",
  "Colossus (Ultimate)",
  "Confederates of the Curious",
  "Constrictor",
  "Contessa (Vera Vidal)",
  "Controller",
  "Cornelius",
  "Corsair",
  "Cosmo (dog)",
  "Cottonmouth",
  "Count Nefaria",
  "Countess",
  "Crimson Crusader",
  "Crimson Dynamo",
  "Crimson Dynamo (Iron Man 3 - The Official Game)",
  "Crimson King",
  "Crossbones",
  "Crule",
  "Crusher Hogan",
  "Crusher Hogan (Ultimate)",
  "Crystal",
  "Cuckoo",
  "Curt Conners",
  "Cuthbert",
  "Cyber",
  "Cyclops",
  "Cyclops (Ultimate)",
  "Cyclops (X-Men: Battle of the Atom)",
  "Cypher",
  "D'Ken Neramani",
  "Dagger",
  "Daily Bugle",
  "Daimon Hellstrom",
  "Daken",
  "Dakota North",
  "Damage Control",
  "Dani Moonstar",
  "Danny Rand",
  "Daredevil",
  "Beast",
  "Beast (Earth-311)",
  "Beast (Ultimate)",
  "Becatron",
  "Bedlam",
  "Beef",
  "Beetle (Abner Jenkins)",
  "Belasco",
  "Ben Grimm",
  "Ben Parker",
  "Ben Reilly",
  "Ben Urich",
  "Bengal",
  "Beta-Ray Bill",
  "Bethany Cabe",
  "Betty Brant",
  "Betty Ross",
  "Beyonder",
  "Bi-Beast",
  "Big Bertha",
  "Big Wheel",
  "Bill Hollister",
  "Bishop",
  "Bishop (Ultimate)",
  "Black Bird",
  "Black Bolt",
  "Black Bolt (Marvel War of Heroes)",
  "Black Cat",
  "Black Cat (Ultimate)",
  "Black Crow",
  "Black Knight (Dane Whitman)",
  "Black Knight (Sir Percy of Scandia)",
  "Black Panther",
  "Black Panther (Shuri)",
  "Black Panther (Ultimate)",
  "Black Queen",
  "Black Tarantula",
  "Black Tom",
  "Black Widow",
  "Black Widow (LEGO Marvel Super Heroes)",
  "Black Widow (Ultimate)",
  "Black Widow (Yelena Belova)",
  "Black Widow/Natasha Romanoff (MAA)",
  "Blackheart",
  "Blacklash",
  "Blackout",
  "Blade",
  "Blastaar",
  "Blazing Skull",
  "Blindfold",
  "Bling!",
  "Blink",
  "Blizzard",
  "Blob",
  "Blob (Ultimate)",
  "Blockbuster",
  "Blok",
  "Bloke",
  "Blonde Phantom",
  "Bloodaxe",
  "Bloodscream",
  "Bloodstorm",
  "Bloodstrike",
  "Blue Blade",
  "Blue Marvel",
  "Blue Shield",
  "Blur",
  "Bob, Agent of Hydra",
  "Boom Boom",
  "Boomer",
  "Boomerang",
  "Box",
  "Bride of Nine Spiders (Immortal Weapons)",
  "Bromley",
  "Brood",
  "Brother Voodoo",
  "Brotherhood of Evil Mutants",
  "Brotherhood of Mutants (Ultimate)",
  "Bruce Banner",
  "Brute",
  "Bucky",
  "Bug",
  "Bulldozer",
  "Bullseye",
  "Bushwacker",
  "Butterfly",
  "Cable",
  "Cable (Deadpool)",
  "Cable (Marvel: Avengers Alliance)",
  "Cable (Ultimate)",
  "Cable (X-Men: Battle of the Atom)",
  "Calamity",
  "Caliban",
  "Callisto",
  "Callisto (Age of Apocalypse)",
  "Calypso",
  "Cammi",
  "Cannonball",
  "Cap'n Oz",
  "Captain America",
  "Iron Fist (Danny Rand)",
  "Iron Fist (Orson Randall)",
  "Iron Fist (Quan Yaozu)",
  "Iron Fist (USM)",
  "Iron Fist (Wu Ao-Shi)",
  "Iron Lad",
  "Iron Man",
  "Iron Man (Iron Man 3 - The Official Game)",
  "Iron Man (LEGO Marvel Super Heroes)",
  "Iron Man (Marvel Heroes)",
  "Iron Man (Marvel War of Heroes)",
  "Iron Man (Ultimate)",
  "Iron Man/Tony Stark (MAA)",
  "Iron Monger",
  "Iron Patriot",
  "Iron Patriot (James Rhodes)",
  "Ironclad",
  "Ironheart (Riri Williams)",
  "Isaiah Bradley",
  "J. Jonah Jameson",
  "Jack Flag",
  "Jack Murdock",
  "Jack O' Lantern",
  "Jack Power",
  "Jackal",
  "Jackpot",
  "James Buchanan Barnes",
  "James Howlett",
  "Jamie Braddock",
  "Jane Foster",
  "Janus, the Nega-Man",
  "Jasper Sitwell",
  "Jazinda",
  "Jean Grey",
  "Jean Grey",
  "Jean Grey (Ultimate)",
  "Jennifer Smith",
  "Jeryn Hogarth",
  "Jessica Drew",
  "Jessica Jones",
  "Jetstream",
  "Jigsaw",
  "Jimmy Woo",
  "Joan the Mouse",
  "Jocasta",
  "John Farson",
  "John Jameson",
  "John Porter",
  "John Wraith",
  "Johnny Blaze",
  "Johnny Storm",
  "Joseph",
  "Joshua Kane",
  "Josiah X",
  "Joystick",
  "Jubilee",
  "Jubilee (Age of Apocalypse)",
  "Juggernaut",
  "Jule Carpenter",
  "Julian Keller",
  "Junta",
  "Justice",
  "Justin Hammer",
  "Ka-Zar",
  "Kabuki",
  "Kang",
  "Karen O'Malley",
  "Karen Page",
  "Karma",
  "Karnak",
  "Karolina Dean",
  "Kat Farrell",
  "Kate Bishop",
  "Katie Power",
  "Ken Ellis",
  "Khan",
  "Kid Colt",
  "Killer Shrike",
  "Killmonger",
  "Killraven",
  "King Bedlam",
  "King Cobra",
  "Kingpin",
  "Kinsey Walden",
  "Kitty Pryde",
  "Kitty Pryde (X-Men: Battle of the Atom)",
  "Klaw",
  "Komodo (Melati Kusuma)",
  "Korath",
  "Korg",
  "Korvac",
  "Krakoa",
  "Kraven the Hunter",
  "Kree",
  "Krista Starr",
  "Kronos",
  "Kulan Gath",
  "Kwannon",
  "Kylun",
  "La Nuit",
  "Lady Bullseye",
  "Lady Deathstrike",
  "Lady Mastermind",
  "Lady Ursula",
  "Lady Vermin",
  "Lake",
  "Landau",
  "Lava-Man",
  "Layla Miller",
  "Leader",
  "Leech",
  "Legion",
  "Lei Kung, The Thunderer",
  "Lenny Balinger",
  "Leo (Zodiac)",
  "Leopardon",
  "Leper Queen",
  "Lester",
  "Lethal Legion",
  "Lieutenant Marcus Stone",
  "Lifeguard",
  "Lightning Lords of Nepal",
  "Lightspeed",
  "Lila Cheney",
  "Lilandra",
  "Lilith",
  "Lily Hollister",
  "Lionheart",
  "Living Laser",
  "Living Lightning",
  "Living Mummy",
  "Living Tribunal",
  "Liz Osborn",
  "Lizard",
  "Lizard (Ultimate)",
  "Loa",
  "Lockheed",
  "Lockjaw",
  "Logan",
  "Loki",
  "Loki (LEGO Marvel Super Heroes)",
  "Loners",
  "Longshot",
  "Longshot (Ultimate)",
  "Lord Hawal",
  "Lord Tyger",
  "Lords of Avalon",
  "Lorna Dane",
  "Luckman",
  "Lucky Pierre",
  "Lucy in the Sky",
  "Luke Cage",
  "Luminals",
  "Luna Snow (Luna Snow)",
  "Lyja",
  "M (Monet St. Croix)",
  "M.O.D.A.M.",
  "M.O.D.O.G.",
  "M.O.D.O.K.",
  "M.O.D.O.K. (Iron Man 3 - The Official Game)",
  "Ma Gnuci",
  "Mac Gargan",
  "Mach IV",
  "Machine Man",
  "Mad Thinker",
  "Madame Hydra",
  "Madame Masque",
  "Madame Web (Julia Carpenter)",
  "Maddog",
  "Madelyne Pryor",
  "Madripoor",
  "Madrox",
  "Maelstrom",
  "Maestro",
  "Magdalene",
  "Maggott",
  "Magik (Amanda Sefton)",
  "Magik (Illyana Rasputin)",
  "Maginty",
  "Magma (Amara Aquilla)",
  "Magneto",
  "Magneto (Age of Apocalypse)",
  "Magneto (House of M)",
  "Magneto (Ultimate)",
  "Magneto (X-Men: Battle of the Atom)",
  "Magus (Adam Warlock)",
  "Magus (Technarch)",
  "Major Mapleleaf",
  "Makkari",
  "Malcolm Colcord",
  "Malekith",
  "Malice (Earth-161)",
  "Man-Thing",
  "Man-Wolf",
  "Mandarin",
  "Mandrill",
  "Mandroid",
  "Manta",
  "Mantis",
  "Marauders",
  "Marcus Van Sciver",
  "Maria Hill",
  "Mariko Yashida",
  "Marrow",
  "Marten Broadcloak",
  "Martin Li",
  "Marvel Apes",
  "Marvel Boy",
  "Marvel Zombies",
  "Marvex",
  "Mary Jane Watson",
  "Mary Jane Watson (House of M)",
  "Mary Jane Watson (Ultimate)",
  "Masked Marvel (Unrevealed)",
  "Masque",
  "Master Chief",
  "Master Mold",
  "Mastermind",
  "Masters of Evil",
  "Mathemanic",
  "Matsu'o Tsurayaba",
  "Matthew Murdock",
  "Mattie Franklin",
  "Mauler",
  "Maverick (Chris Bradley)",
  "Maverick (Christoph Nord)",
  "Maximus",
  "May Parker",
  "Medusa",
  "Meggan",
  "Meltdown",
  "Menace",
  "Mentallo",
  "Mentor",
  "Mephisto",
  "Mephistopheles",
  "Mercury",
  "Mesmero",
  "Metal Master",
  "Meteorite",
  "MI: 13",
  "Micro/Macro",
  "Microbe",
  "Microchip",
  "Micromax",
  "Midnight (Earth-811)",
  "Miek",
  "Mikhail Rasputin",
  "Millenium Guard",
  "Millie the Model",
  "Mimic",
  "Mindworm",
  "Miracleman",
  "Miss America",
  "Mister Fear",
  "Mister Sinister",
  "Mister Sinister (Deadpool)",
  "Mister Sinister (House of M)",
  "Mister Sinister (Ultimate)",
  "Misty Knight",
  "Mockingbird",
  "Moira MacTaggert",
  "Moira MacTaggert (Ultimate)",
  "Mojo",
  "Mole Man",
  "Molecule Man",
  "Molly Hayes",
  "Molly Von Richtofen",
  "Molten Man",
  "Mongoose",
  "Mongu (Unrevealed)",
  "Monster Badoon",
  "Moon Girl (Lunella Layfayette)",
  "Moon Knight",
  "Moon Knight (House of M)",
  "Moon Knight (Ultimate)",
  "Moondragon",
  "Moonstone",
  "Morbius",
  "Mordo",
  "Morg",
  "Morgan Le Fay",
  "Morgan Stark",
  "Morlocks",
  "Morlun",
  "Morph",
  "Mother Askani",
  "Mr. Bumpo",
  "Mr. Fantastic",
  "Mr. Fantastic (Ultimate)",
  "Mr. Fish",
  "Mr. Fixit",
  "Mr. Hyde",
  "Mr. Immortal",
  "Mr. Meugniot",
  "Mr. Negative",
  "Mr. Payback",
  "Mr. X",
  "Ms. America (America Chavez)",
  "Ms. Marvel (Kamala Khan)",
  "MS2",
  "Mulholland Black",
  "Multiple Man",
  "MVP",
  "Mysterio",
  "Mysterio (Daniel Berkhart)",
  "Mysterio (Francis Klum)",
  "Mystique",
  "Mystique (Age of Apocalypse)",
  "Mystique (House of M)",
  "Mystique (Ultimate)",
  "Nakia (Nakia)",
  "Namor",
  "Namora",
  "Namorita",
  "Naoko",
  "Natasha Romanoff",
  "Nebula",
  "Nehzno",
  "Nekra",
  "Nemesis",
  "Network",
  "New Goblin",
  "New Mutants",
  "New Warriors",
  "New X-Men",
  "Newton Destine",
  "Next Avengers",
  "Nextwave",
  "Nick Fury",
  "Nick Fury (LEGO Marvel Super Heroes)",
  "Nick Fury (Ultimate)",
  "Nico Minoru",
  "Nicolaos",
  "Night Nurse (Earth-9997)",
  "Night Nurse (Linda Carter)",
  "Night Thrasher",
  "Night Thrasher (Dwayne Taylor)",
  "Nightcrawler",
  "Nightcrawler (Ultimate)",
  "Nighthawk",
  "Nightmare",
  "Nightshade",
  "Nine-Fold Daughters of Xao",
  "Nitro",
  "Nocturne",
  "Nomad",
  "Nomad (Rikki Barnes)",
  "Nomad (Steve Rogers)",
  "Norman Osborn",
  "Norrin Radd",
  "Northstar",
  "Nova",
  "Nova (Frankie Raye)",
  "Nova (Sam Alexander)",
  "Nova (USM)",
  "Nuke",
  "Obadiah Stane",
  "Odin",
  "Ogun",
  "Okoye",
  "Old Lace",
  "Old Man Logan (Earth-807128)",
  "Omega (Michael Pointer)",
  "Omega Flight",
  "Omega Red",
  "Omega Sentinel",
  "Omega the Unknown",
  "Onslaught",
  "Onslaught (Ultimate)",
  "Oracle",
  "Ord",
  "Orphan",
  "Orphan-Maker",
  "Otto Octavius",
  "Outlaw (Inez Temple)",
  "Outlaw Kid",
  "Overlord",
  "Owl",
  "Ozymandias",
  "Paibok",
  "Paladin",
  "Pandemic",
  "Paper Doll",
  "Patch",
  "Patriot",
  "Payback",
  "Peggy Carter (Captain Carter)",
  "Penance (Monet St. Croix)",
  "Penance (Robert Baldwin)",
  "Pepper Potts",
  "Pestilence",
  "Pet Avengers",
  "Pete Wisdom",
  "Peter Parker",
  "Peter Quill",
  "Phalanx",
  "Phantom Reporter",
  "Phil Coulson (Phil Coulson)",
  "Phil Sheldon",
  "Phoenix Force",
  "Photon",
  "Phyla-Vell",
  "Piledriver",
  "Pip",
  "Pixie",
  "Plazm",
  "Polaris",
  "Post",
  "Power Man (USM)",
  "Power Pack",
  "Praxagora",
  "Preak",
  "Pretty Boy",
  "Pride",
  "Prima",
  "Prince of Orphans",
  "Princess Powerful",
  "Prism",
  "Prodigy",
  "Prodigy (David Alleyne)",
  "Proemial Gods",
  "Professor Monster",
  "Professor X",
  "Professor X (Ultimate)",
  "Proteus",
  "Proteus (House of M)",
  "Proteus (Ultimate)",
  "Proudstar",
  "Prowler",
  "Prowler (Rick Lawson)",
  "Psycho-Man",
  "Psylocke",
  "PsyNapse",
  "Puck",
  "Puck (Zuzha Yu)",
  "Puff Adder",
  "pug",
  "Puma",
  "Punisher",
  "Punisher (2099)",
  "Punisher (Marvel: Avengers Alliance)",
  "Puppet Master",
  "Purifiers",
  "Purple Man",
  "Pyro",
  "Quake (Daisy Johnson)",
  "Quasar (Phyla-Vell)",
  "Quasar (Wendell Vaughn)",
  "Quasimodo",
  "Queen Noir",
  "Quentin Quire",
  "Quicksilver",
  "Quicksilver (Age of Apocalypse)",
  "Quicksilver (Ultimate)",
  "Rachel Grey",
  "Radioactive Man",
  "Rafael Vega",
  "Rage",
  "Raider",
  "Randall",
  "Randall Flagg",
  "Random",
  "Rattler",
  "Ravenous",
  "Rawhide Kid",
  "Raza",
  "Reaper",
  "Reavers",
  "Reavers (Ultimate)",
  "Red 9",
  "Red Ghost",
  "Red Ghost (Ultimate)",
  "Red Guardian (Alexei Shostakov)",
  "Red Hulk",
  "Red Hulk (HAS)",
  "Red She-Hulk",
  "Red Shift",
  "Red Skull",
  "Red Skull (Albert Malik)",
  "Red Wolf",
  "Redwing",
  "Reptil",
  "Retro Girl",
  "Revanche",
  "Rhino",
  "Rhodey",
  "Richard Fisk",
  "Rick Jones",
  "Rick Jones (Ultimate)",
  "Ricochet",
  "Rictor",
  "Riptide",
  "Risque",
  "Robbie Robertson",
  "Robert Baldwin",
  "Robin Chapel",
  "Rocket Raccoon",
  "Rocket Raccoon (Marvel Heroes)",
  "Rocket Racer",
  "Sunset Bain",
  "Sunspot",
  "Super Hero Squad",
  "Super-Adaptoid",
  "Super-Skrull",
  "Supernaut",
  "Supreme Intelligence",
  "Surge",
  "Surtur",
  "Susan Delgado",
  "Swarm",
  "Sway",
  "Switch",
  "Sword Master (Sword Master)",
  "Swordsman",
  "Swordsman (Jacques Duquesne)",
  "Sym",
  "Synch",
  "T'Challa",
  "Tag",
  "Talisman (Elizabeth Twoyoungmen)",
  "Talkback (Chase Stein)",
  "Talon (Fraternity of Raptors)",
  "Talos",
  "Tana Nile",
  "Tarantula (Luis Alvarez)",
  "Tarantula (Maria Vasquez)",
  "Tarot",
  "Taskmaster",
  "Tattoo",
  "Taurus (Cornelius van Lunt)",
  "Technarchy",
  "Ted Forrester",
  "Tempest",
  "Tenebrous",
  "Terrax",
  "Terror",
  "Texas Twister",
  "Thaddeus Ross",
  "Thanos",
  "Thanos (Ultimate)",
  "The 198",
  "The Anarchist",
  "The Call",
  "The Captain",
  "The Collector (Taneleer Tivan)",
  "The Enforcers",
  "The Executioner",
  "The Fallen",
  "The Fury",
  "The Hand",
  "The Hood",
  "The Howling Commandos",
  "The Hunter",
  "The Initiative",
  "The Leader (HAS)",
  "The Liberteens",
  "The Liberty Legion",
  "The Order",
  "The Phantom",
  "The Professor",
  "The Renegades",
  "The Santerians",
  "The Shiver Man",
  "The Spike",
  "The Stranger",
  "The Twelve",
  "The Watchers",
  "Thena",
  "Thing",
  "Thing (Marvel Heroes)",
  "Thing (Ultimate)",
  "Thor",
  "Thor (Goddess of Thunder)",
  "Thor (MAA)",
  "Thor (Marvel Heroes)",
  "Thor (Marvel War of Heroes)",
  "Thor (Marvel: Avengers Alliance)",
  "Thor (Ultimate)",
  "Thor Girl",
  "Thunderball",
  "Thunderbird (John Proudstar)",
  "Thunderbird (Neal Shaara)",
  "Thunderbolt (Bill Carver)",
  "Thunderbolt Ross",
  "Thunderbolts",
  "Thundra",
  "Tiger Shark",
  "Tiger's Beautiful Daughter",
  "Tigra (Greer Nelson)",
  "Timeslip",
  "Tinkerer",
  "Tippy Toe",
  "Titania",
  "Titanium Man (Topolov)",
  "Toad",
  "Toad Men",
  "Tomas",
  "Tombstone",
  "Tomorrow Man",
  "Rockslide",
  "Rogue",
  "Rogue (Age of Apocalypse)",
  "Rogue (Deadpool)",
  "Rogue (Ultimate)",
  "Rogue (X-Men: Battle of the Atom)",
  "Roland Deschain",
  "Romulus",
  "Ronan",
  "Ronin",
  "Roughhouse",
  "Roulette",
  "Roxanne Simpson",
  "Rumiko Fujikawa",
  "Runaways",
  "Russian",
  "S.H.I.E.L.D.",
  "Sabra",
  "Sabretooth",
  "Sabretooth (Age of Apocalypse)",
  "Sabretooth (House of M)",
  "Sabretooth (Ultimate)",
  "Sage",
  "Salem's Seven (Ultimate)",
  "Sally Floyd",
  "Salo",
  "Sandman",
  "Santa Claus",
  "Saracen (Muzzafar Lambert)",
  "Sasquatch (Walter Langkowski)",
  "Satana",
  "Sauron",
  "Scalphunter",
  "Scarecrow (Ebenezer Laughton)",
  "Scarlet Spider (Ben Reilly)",
  "Scarlet Spider (Kaine)",
  "Scarlet Witch",
  "Scarlet Witch (Age of Apocalypse)",
  "Scarlet Witch (Marvel Heroes)",
  "Scarlet Witch (Ultimate)",
  "Scorpion (Carmilla Black)",
  "Scorpion (Mac Gargan)",
  "Scorpion (Ultimate)",
  "Scourge",
  "Scrambler",
  "Scream (Donna Diego)",
  "Screwball",
  "Sebastian Shaw",
  "Secret Warriors",
  "Selene",
  "Senator Kelly",
  "Sentinel",
  "Sentinels",
  "Sentry (Robert Reynolds)",
  "Ser Duncan",
  "Serpent Society",
  "Sersi",
  "Shadow King",
  "Shadow King (Age of Apocalypse)",
  "Shadowcat",
  "Shadowcat (Age of Apocalypse)",
  "Shadowcat (Ultimate)",
  "Shadu the Shady",
  "Shalla-bal",
  "Shaman",
  "Shane Yamada-Jones",
  "Shang-Chi",
  "Shang-Chi (Ultimate)",
  "Shanna the She-Devil",
  "Shape",
  "Shard",
  "Sharon Carter",
  "Sharon Ventura",
  "Shatterstar",
  "She-Hulk (HAS)",
  "She-Hulk (Jennifer Walters)",
  "She-Hulk (Lyra)",
  "She-Hulk (Marvel War of Heroes)",
  "She-Hulk (Ultimate)",
  "Shen",
  "Sheva Callister",
  "Shi'Ar",
  "Shinko Yamashiro",
  "Shinobi Shaw",
  "Shiva",
  "Shiver Man",
  "Shocker (Herman Schultz)",
  "Shockwave",
  "Shooting Star",
  "Shotgun",
  "Shriek",
  "Sif",
  "Silhouette",
  "Silk (Cindy Moon)",
  "Silk Fever",
  "Silver Centurion",
  "Silver Fox",
  "Silver Sable",
  "Silver Samurai",
  "Silver Samurai (Age of Apocalypse)",
  "Tony Stark",
  "Toro (Thomas Raymond)",
  "Toxin",
  "Toxin (Eddie Brock)",
  "Trauma",
  "Trevor Fitzroy",
  "Triathlon",
  "Trish Tilby",
  "Triton",
  "True Believers",
  "Turbo",
  "Tusk",
  "Two-Gun Kid",
  "Tyger Tiger",
  "Typhoid Mary",
  "Tyrannus",
  "U-Foes",
  "U-Go Girl",
  "U.S. Agent",
  "Uatu The Watcher",
  "Ulik",
  "Ultimate Spider-Man (USM)",
  "Ultimates",
  "Ultimatum",
  "Ultimo",
  "Ultra-Adaptoid",
  "Ultragirl (Earth-93060)",
  "Ultron",
  "Umar",
  "Unicorn",
  "Union Jack (Brian Falsworth)",
  "Union Jack (Joseph Chapman)",
  "Union Jack (Montgomery Falsworth)",
  "Unus",
  "Unus (Age of Apocalypse)",
  "Unus (House of M)",
  "Unus (Ultimate)",
  "Valeria Richards",
  "Valkyrie (Exiles)",
  "Valkyrie (Samantha Parrington)",
  "Valkyrie (Ultimate)",
  "Vampiro",
  "Vance Astro",
  "Vanisher (Age of Apocalypse)",
  "Vanisher (Telford Porter)",
  "Vanisher (Ultimate)",
  "Vapor",
  "Vargas",
  "Vector",
  "Veda",
  "Vengeance (Michael Badilino)",
  "Venom (Flash Thompson)",
  "Venom (Mac Gargan)",
  "Venom (Ultimate)",
  "Venus (Siren)",
  "Venus Dee Milo",
  "Vermin (Edward Whelan)",
  "Vertigo (Savage Land Mutate)",
  "Victor Mancha",
  "Victor Von Doom",
  "Vin Gonzales",
  "Vindicator",
  "Violations",
  "Viper",
  "Virginia Dare",
  "Vision",
  "Vivisector",
  "Vulcan (Gabriel Summers)",
  "Vulture (Adrian Toomes)",
  "Vulture (Blackie Drago)",
  "Wallflower",
  "Wallop",
  "Wallow",
  "War (Abraham Kieros)",
  "War Machine (Iron Man 3 - The Official Game)",
  "War Machine (James Rhodes)",
  "War Machine (Marvel: Avengers Alliance)",
  "War Machine (Parnell Jacobs)",
  "War Machine (Ultimate)",
  "Warbird",
  "Warbound",
  "Warhawk (Mitchell Tanner)",
  "Warlock (Janie Chin)",
  "Warlock (Technarchy)",
  "Warpath",
  "Warren Worthington III",
  "Warstar",
  "Wasp",
  "Wasp (Ultimate)",
  "Wave (Wave)",
  "Weapon Omega",
  "Weapon X",
  "Wendell Rand",
  "Wendell Vaughn",
  "Wendigo",
  "Werewolf By Night",
  "Whiplash (Anton Vanko)",
  "Whiplash (Mark Scarlotti)",
  "Whirlwind",
  "Whistler",
  "Silver Surfer",
  "Silverclaw",
  "Silvermane",
  "Sin",
  "Sinister Six",
  "Sir Ram",
  "Siren (Earth-93060)",
  "Sister Grimm",
  "Skaar",
  "Skaar (HAS)",
  "Skin",
  "Skreet",
  "Skrulls",
  "Skrulls (Ultimate)",
  "Skullbuster (Cylla Markham)",
  "Slapstick",
  "Slayback",
  "Sleeper",
  "Sleepwalker",
  "Slipstream",
  "Slyde",
  "Smasher (Vril Rokk)",
  "Smiling Tiger",
  "Snowbird",
  "Solo (James Bourne)",
  "Songbird",
  "Sons of the Tiger",
  "Spacker Dave",
  "Spectrum",
  "Speed",
  "Speed Demon",
  "Speedball (Robert Baldwin)",
  "Spencer Smythe",
  "Sphinx (Anath-Na Mut)",
  "Spider-dok",
  "Spider-Girl (Anya Corazon)",
  "Spider-Girl (May Parker)",
  "Spider-Gwen (Gwen Stacy)",
  "Spider-Ham (Larval Earth)",
  "Spider-Man (1602)",
  "Spider-Man (2099)",
  "Spider-Man (Ai Apaec)",
  "Spider-Man (Ben Reilly)",
  "Spider-Man (House of M)",
  "Spider-Man (LEGO Marvel Super Heroes)",
  "Spider-Man (Marvel Zombies)",
  "Spider-Man (Marvel: Avengers Alliance)",
  "Spider-Man (Miles Morales)",
  "Spider-Man (Noir)",
  "Spider-Man (Peter Parker)",
  "Spider-Man (Takuya Yamashiro)",
  "Spider-Man (Ultimate)",
  "Spider-Woman (Charlotte Witter)",
  "Spider-Woman (Jessica Drew)",
  "Spider-Woman (Mattie Franklin)",
  "Spiral (Rita Wayword)",
  "Spirit",
  "Spitfire",
  "Spot",
  "Sprite",
  "Spyke",
  "Squadron Sinister",
  "Squadron Supreme (Earth-712)",
  "Squirrel Girl",
  "Stacy X",
  "Stacy X (Ultimate)",
  "Star Brand",
  "Star-Lord (Peter Quill)",
  "Starbolt",
  "Stardust",
  "Starfox",
  "Starhawk (Stakar Ogord)",
  "Starjammers",
  "Stark Industries",
  "Stature",
  "Steel Serpent (Davos)",
  "Stegron",
  "Stellaris",
  "Stepford Cuckoos",
  "Stephanie de la Spiroza",
  "Stephen Strange",
  "Steve Rogers",
  "Stick",
  "Stilt-Man (Wibur Day)",
  "Stingray (Walter Newell)",
  "Stone Men",
  "Storm",
  "Storm (Age of Apocalypse)",
  "Storm (Marvel Heroes)",
  "Storm (Ultimate)",
  "Stranger",
  "Strong Guy",
  "Stryfe",
  "Stryfe (Ultimate)",
  "Sub-Mariner",
  "Sue Storm",
  "Sugar Man",
  "Sumo",
  "Sunfire",
  "Sunfire (Age of Apocalypse)",
  "White Queen (Adrienne Frost)",
  "White Tiger (Angela Del Toro)",
  "White Tiger (USM)",
  "Whizzer (Stanley Stewart)",
  "Wiccan",
  "Wild Child",
  "Wild Child (Age of Apocalypse)",
  "Wild Pack",
  "Wildside",
  "William Stryker",
  "Wilson Fisk",
  "Wind Dancer",
  "Winter Soldier",
  "Wither",
  "Wolf Cub",
  "Wolfpack",
  "Wolfsbane",
  "Wolfsbane (Age of Apocalypse)",
  "Wolver-dok",
  "Wolverine",
  "Wolverine (LEGO Marvel Super Heroes)",
  "Wolverine (Marvel War of Heroes)",
  "Wolverine (Ultimate)",
  "Wolverine (X-Men: Battle of the Atom)",
  "Wonder Man",
  "Wong",
  "Wong (Ultimate)",
  "Wraith",
  "Wrecker",
  "Wrecking Crew",
  "X-23",
  "X-51",
  "X-Babies",
  "X-Cutioner",
  "X-Factor",
  "X-Factor Investigations",
  "X-Force",
  "X-Man",
  "X-Men",
  "X-Men (Ultimate)",
  "X-Ray (James Darnell)",
  "X-Statix",
  "X.S.E.",
  "Xavin",
  "Xorn (Kuan-Yin Xorn)",
  "Yellow Claw",
  "Yellowjacket (Hank Pym)",
  "Yellowjacket (Rita DeMara)",
  "Yondu",
  "Young Avengers",
  "Young X-Men",
  "Zaladane",
  "Zaran",
  "Zarda",
  "Zarek",
  "Zeigeist",
  "Zemo",
  "Zeus",
  "Zodiak",
  "Zombie (Simon Garth)",
  "Zuras",
  "Zzzax",
];
